import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Profs Rated AI",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
 

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
      </ClerkProvider>
  );
}
